# Gitleaks configuration for allowlisting detected secrets
# These secrets were detected in files that no longer exist but the commits remain

[[ rules ]]
    id = "curl-auth-header"
    [ rules.allowlist ]
        commits = [
            "37bbb045e7c4cbda32ed9894e53475553da83a0b",  # Remove extra docs and example directory
            "dd01efc558aac6cb3724f46cc5b97a124dde78e3",  # Update templates and docs to be more MCP engineer focused
            "0ddbd71c1d29609e9c9901fe9ca1d41ac92fdf9a",  # Add example connectors and queries for 80% of known MCP use cases
            "0d722f28d74020dd8a09f2f7b736fd39e745c4ab",  # Add the mcp augmentation to rover-init-starters
            "5035981f16d73efc604e91694cd9f8daa904d19c",  # Re-include the claude-desktop-config file for quick setup
            "9e1c6ae02233a1f5d2578fed8cbca4788454e7ca"   # Update example tools and remove platform-specific ai client references
        ]

[[ rules ]]
    id = "apollo-graphos-api-key"
    [ rules.allowlist ]
        commits = [
            "37bbb045e7c4cbda32ed9894e53475553da83a0b",  # Remove extra docs and example directory
            "dd01efc558aac6cb3724f46cc5b97a124dde78e3",  # Update templates and docs to be more MCP engineer focused
            "0ddbd71c1d29609e9c9901fe9ca1d41ac92fdf9a",  # Add example connectors and queries for 80% of known MCP use cases
            "0d722f28d74020dd8a09f2f7b736fd39e745c4ab",  # Add the mcp augmentation to rover-init-starters
            "5035981f16d73efc604e91694cd9f8daa904d19c",  # Re-include the claude-desktop-config file for quick setup
            "9e1c6ae02233a1f5d2578fed8cbca4788454e7ca"   # Update example tools and remove platform-specific ai client references
        ]